ruby-numo/numo-narray

- Rakefile
The following problems are fixed with this change:
* Ruby 2.4 isn't supported. (The latest rake-compiler-dock supports Ruby 2.4. If we specify `RUBY_CC_VERSION` explicitly, Ruby 2.4 support isn't disabled.)
* Infinite dependency loop. (`windows_gem_paths` -> `build:windows` dependency causes `rake build:windows` -> `windows_gem_paths` -> `rake build:windows` -> ... loop.)
> Remove needless configurations for fat gems

- ext/numo/narray/numo/narray.h
Hi,
this PR puts an extern "C" declaration in narray.h for C++ compilers.
When we write ruby eternal libraries in C++ using NArray C API directly (e.g. for performance reasons), this PR is convenient.
Regards.
> use extern "C" in narray.h for C++ compilers.

- lib/erbpp/line_number.rb
On Ruby 2.5.0, the code generated by ERB was changed.
It broke the code generation of numo-narray.
> Support ruby 2.5.0

- ext/numo/narray/narray.c
I found the check of writing to a frozen object is duplicated.
> Remove duplicated check

- ext/numo/narray/data.c
- ext/numo/narray/gen/tmpl/alloc_func.c
- ext/numo/narray/gen/tmpl/each.c
- ext/numo/narray/gen/tmpl/each_with_index.c
- ext/numo/narray/gen/tmpl/inspect.c
- ext/numo/narray/gen/tmpl/map_with_index.c
- ext/numo/narray/gen/tmpl/qsort.c
- ext/numo/narray/gen/tmpl/to_a.c
- ext/numo/narray/gen/tmpl_bit/each.c
- ext/numo/narray/gen/tmpl_bit/each_with_index.c
- ext/numo/narray/gen/tmpl_bit/inspect.c
- ext/numo/narray/gen/tmpl_bit/to_a.c
- ext/numo/narray/index.c
- ext/numo/narray/math.c
- ext/numo/narray/narray.c
- ext/numo/narray/ndloop.c
- ext/numo/narray/rand.c
- ext/numo/narray/step.c
- ext/numo/narray/struct.c
and remove unused functions.
This is a kind of **feedbacks** from Cumo to Numo.
I am currently creating CUDA-aware version of Numo, https://github.com/sonots/cumo.
I want to support conversion from Numo::NArray into Cumo::NArray.
To do it, I needed to support `require "numo/narray.so"` anyway.
I needed to resolve C symbol collisions between Numo and Cumo.
While working to resolve symbol conflictions, I noticed that some functions are not used from outside of its file. So, I put `static` for them. I also found that some C functions are even not used from anywhere. So, I removed them.
https://github.com/sonots/cumo/pull/48
> Add static to functions that not necessary to be exported

- ext/numo/narray/gen/tmpl/binary.c
I wrote a patch to improve the performance of the broadcast.
(See #93 for details.)
```
$ cat broadcast_fp32_0.rb
require 'benchmark'
require 'numo/narray'
num_iteration = 10000
Benchmark.bm 20 do |r|
x = Numo::SFloat.ones([1000,784])
y = Numo::SFloat.ones([1000,784])
r.report "x.inplace + y" do
num_iteration.times do
x.inplace + y
end
end
x = Numo::SFloat.ones([1000,784])
y = Numo::SFloat.ones([1000,784])
r.report "x.inplace + 1.0" do
num_iteration.times do
x.inplace + 1.0
end
end
x = Numo::SFloat.ones([1000,784])
z = Numo::SFloat.ones([1000,1])
r.report "x.inplace + z" do
num_iteration.times do
x.inplace + z
end
end
x = Numo::SFloat.ones([1000,784])
y = Numo::SFloat.ones([1000,784])
r.report "x.inplace - y" do
num_iteration.times do
x.inplace - y
end
end
x = …
```
> Broadcast performance improvement.

- Rakefile
- ext/numo/narray/extconf.rb
Because we specify "~> 2.1" in gemspec.
We may be able to drop 2.2 or older support in near future. Because
Ruby 2.2 was EOL at 2018-03.
> Require Ruby 2.1 or later

- ext/numo/narray/depend.erb
Can't build current master by "rake build:windows".
I fixed this patch. (See #101 for details.)
```
$ git clone https://github.com/ruby-numo/numo-narray.git
$ cd numo-narray/
$ su
rm -rf tmp/windows
mkdir -p tmp/windows
rake-compiler-dock bash -c "git clone file:///home/naitoh/numo-narray/.git tmp/windows && cd tmp/windows && bundle && rake RUBY_CC_VERSION\\=2.5.0:2.4.0:2.3.0:2.2.2:2.1.6 cross native gem"
Cloning into 'tmp/windows'...
remote: Counting objects: 5320, done.
remote: Compressing objects: 100% (1245/1245), done.
remote: Total 5320 (delta 3315), reused 5320 (delta 3315)
Receiving objects: 100% (5320/5320), 1.24 MiB | 6.81 MiB/s, done.
Resolving deltas: 100% (3315/3315), done.
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root …
```
> Fixed "rake build:windows".

- ext/numo/narray/extconf.rb
- ext/numo/narray/gen/cogen.rb
- ext/numo/narray/gen/def/dfloat.rb
- ext/numo/narray/gen/def/sfloat.rb
- ext/numo/narray/gen/spec.rb
- ext/numo/narray/gen/tmpl/binary.c
- ext/numo/narray/gen/tmpl/lib.c
- ext/numo/narray/gen/tmpl/unary_s.c
- ext/numo/narray/numo/template.h
- test/narray_test.rb
I implemented SSE2 support on numo-narray.
* SSE2 support is add / sub / mul / div / sqrt operation of SFloat and DFloat.
* It performs 16 Byte (DFloat(8 Byte) * 2) or (SFloat(4 Byte) * 4) calculations.
* I wanted to omit checking the CPU, so I did SSE support only for 64 bit package.
I have created the numo-narray gems package for confirmation.
0.9.6.0 : master (b624b047acf92e73026ea4b72210fdfb165c33ae)
0.9.7.5 : simd support build (this pull request)
```
$ gem install benchmark_driver
$ gem install numo-narray # (0.9.0.3(Windows), 0.9.1.2(Linux/Mac), 0.9.6.0, 0.9.7.5)
$ benchmark-driver simd_fp32_add_sum_mul_div.yaml -o markdown
$ benchmark-driver simd_fp32_sqrt.yaml -o markdown
```
```
$ cat simd_fp32_add_sum_mul_div.yaml 
contexts:
- gems: { numo-narray: 0.9.1.2 }
require: false …
```
> Performance improvement of add/sub/mul/div/sqrt by SIMD calculation (64bit OS only)

- lib/numo/narray/extra.rb
- test/narray_test.rb
I found that the `k` argument of the `triu_indices` does not enable. As a result, the matrix returned by the `tril` method has zeros along diagonal elements. It is not a [lower triangular matrix](http://mathworld.wolfram.com/LowerTriangularMatrix.html).
```ruby
> require ‘numo/narray’
=> true
> a=Numo::DFloat.new(3,3).rand
=> Numo::DFloat#shape=[3,3]
[[0.0617545, 0.373067, 0.794815],
[0.201042, 0.116041, 0.344032],
[0.539948, 0.737815, 0.165089]]
> a.tril
=> Numo::DFloat#shape=[3,3]
[[0, 0, 0],
[0.201042, 0, 0],
[0.539948, 0.737815, 0]]
> a.triu_indices
=> Numo::Int32#shape=[6]
[0, 1, 2, 4, 5, 8]
> a.triu_indices(1)
=> Numo::Int32#shape=[6]
[0, 1, 2, 4, 5, 8]
> a.triu_indices(-1)
=> Numo::Int32#shape=[6]
[0, 1, 2, 4, 5, 8]
```
The cause of this bug is that the `k` argument of the …
> Fix bug in the triu_indices method that the k argument is ignored

- ToDo
- ext/numo/narray/array.c
- ext/numo/narray/extconf.rb
- ext/numo/narray/gen/tmpl/store_array.c
- ext/numo/narray/gen/tmpl_bit/store_array.c
- ext/numo/narray/index.c
- ext/numo/narray/narray.c
- ext/numo/narray/numo/intern.h
- ext/numo/narray/numo/narray.h
- ext/numo/narray/step.c
- test/narray_test.rb
I am working on supporting arithmetic sequences in Ruby 2.6.
Please tell me because there are unclear points in this work.
|   |  | Ruby |  | return |  | Numo slicing support |  | Numo store  support|  |  | api |  |  |  |  |  |  |  |  |
| --- | --- | :---: | :---: | --- | --- | :---: | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
|  object | sample | 2.5 | 2.6 | return (value) | return (class) | now | this PR | now | this PR | to_a(Array) | begin | end | first | first(2) | last | last(2) | step | exclude_end? | length |
|  Array | [1, 3, 5, 7, 9] | o |  |  | Array | o | o | o | o | <= | - | - | 1 | [1, 3] | 9 | [7, 9] | - | - | 10 |
|  Range | 1..10 | o |  | 1..10 | Range | o | o | o | o | [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] | 1 | 10 | 1 | [1, 2] | 10 | [9, …
> [WIP] Arithmetic sequence support.

- ext/numo/narray/numo/narray.h
It prevents `duplicate symbol _rb_cArithSeq` link error.
> extern is needed for the declaration of rb_cArithSeq in narray.h

- ext/numo/narray/gen/spec.rb
- ext/numo/narray/gen/tmpl/at.c
- ext/numo/narray/index.c
- ext/numo/narray/numo/intern.h
- lib/numo/narray/extra.rb
- test/narray_test.rb
I rewrote the at() method using C language.
The result is up to x18 times faster.
* 0.9.2.1 : this PR(3df0b60870258a824e4d6f2e7e9f0e714d69ca9d)
<pre>
$  benchmark-driver diagonal_at_fp32_diff.yaml
Calculating -------------------------------------
numo-narray 0.9.1.4  numo-narray 0.9.2.1 
a.at(Array, Array)                                            546.533               9.840k i/s -      1.000k times in 1.829716s 0.101628s
l.at(Numo::Int32(X).seq,      Numo::Int32(X).seq)              2.203k               7.935k i/s -      1.000k times in 0.453879s 0.126025s
Comparison:
a.at(Array, Array)                               
numo-narray 0.9.2.1:      9839.8 i/s 
numo-narray 0.9.1.4:       546.5 i/s - 18.00x  slower
l.at(Numo::Int32(X).seq,      Numo::Int32(X).seq)
numo-narray 0.9.2.1: …
> at() method was rewritten in C.

- .travis.yml
- ext/numo/narray/index.c
rb_f_notimplement() signature was changed by
https://github.com/ruby/ruby/commit/9ef51b0b89a10c8c401cb9f2337e47a25be72cbe
.
If we use rb_f_notimplement() directly instead of delegating to
rb_f_notimplement(), we can use the same code for Ruby 2.7 or earlier.
> Add support for Ruby 2.7

- ext/numo/narray/gen/tmpl/alloc_func.c
- ext/numo/narray/gen/tmpl/allocate.c
- ext/numo/narray/gen/tmpl_bit/allocate.c
- ext/numo/narray/narray.c
- ext/numo/narray/numo/narray.h
- test/narray_test.rb
It reduces memory usage when NArray just uses data as read only data
because store_binary doesn't copy the passed binary data until NArray
writes the passed binary data.
Benchamrk:
require "numo/narray"
GC.disable
shape = [100, 100]
array = Numo::Int32.new(*shape).seq
data = array.to_binary
frozen_data = array.to_binary.freeze
marshaled_data = Marshal.dump(array)
def report_memory_usage(label, previous)
usage = File.readlines("/proc/self/status").grep(/^VmRSS/)[0][/^VmRSS:\s*(\d+)/, 1].to_i
puts "#{label}: #{usage - previous} kB"
usage
end
usage = report_memory_usage("initial", 0)
10000.times do
Numo::Int32.new(*shape).seq
end
usage = report_memory_usage("seq", usage)
10000.times do
Numo::Int32.from_binary(data, shape)
end
usage = report_memory_usage("from not frozen data", usage) …
> Add support for copy on write with store_binary and frozen string

- README.md
The title of Numo::NArray README is informative. That's a good thing. 
But as a design, it looks a little busy. Why don't we simplify it? 
This is just a suggestion to make README looks clean...
Thank you.
> [README] Simplify the README title

- ext/numo/narray/gen/cogen.rb
The current usage of `open` will not close the file.
> Use File.write in cogen to ensure file is closed

- lib/numo/narray/extra.rb
- test/narray_test.rb
Adds `percentile` method.
```ruby
a = [[1,2,3],[5,7,11]]
a.percentile(50)
a.percentile(50, axis: 0)
a.percentile(50, axis: 1)
```
Uses the C = 1 variant for [percentile](https://en.wikipedia.org/wiki/Percentile) (same as NumPy).
NumPy test code
```py
import numpy as np
x = np.array([[1,2,3],[5,7,11]])
print(np.percentile(x, 0))
print(np.percentile(x, 50))
print(np.percentile(x, 100))
print(np.percentile(x, 0, axis=0))
print(np.percentile(x, 50, axis=0))
print(np.percentile(x, 100, axis=0))
print(np.percentile(x, 0, axis=1))
print(np.percentile(x, 50, axis=1))
print(np.percentile(x, 100, axis=1))
```
> Adds percentile method

- test/narray_test.rb
This is a small follow-up to #158 to ensure the C = 1 variant is used.
> Added more percentile tests

- .gitignore
- Rakefile
- numo-narray.gemspec
Just a suggestion, so feel free to close without comment if there's not any interest. This should make development a bit more standard as well as easier for Mac users (I believe it can eliminate the need for the custom setup scripts).
Edit - Here's the link: https://github.com/rake-compiler/rake-compiler
```sh
bundle exec rake compile
```
On Mac, the current `setup.rb` script doesn't return any errors, but doesn't appear to compile the extension.
```sh
ruby setup.rb compile
(ruby 2.7.1 x86_64-darwin18)
- - COMPILE - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
```
Instead, my workflow as been:
```sh
ruby ext/numo/narray/extconf.rb
make
cp narray.bundle lib/numo/narray.bundle
```
> Use rake-compiler to make development a bit easier

- numo-narray.gemspec
The next Ruby release will be 3.0.0: https://github.com/ruby/ruby/commit/21c62fb670b1646c5051a46d29081523cd782f11
The current `~> 2.2` `required_ruby_version` rejects `3.0.0`.
> Add support for Ruby 3.0

- ext/numo/narray/gen/tmpl/accum_binary.c
- test/narray_test.rb
- test/test_helper.rb
This pull request fixes issue #184.
In Ruby 2.7 and later, it is preferable to use `rb_funcallv_kw` when calling method with keyword arguments. 
master branch:
```ruby
irb(main):001:0> require 'numo/narray'
=> true
irb(main):002:0> a=Numo::Int32[1,2,3]
=>
Numo::Int32#shape=[3]
...
irb(main):003:0> b=Numo::DFloat[[4],[5],[6]]
=>
Numo::DFloat#shape=[3,1]
...
irb(main):004:0> a.dot(b)
/Users/yoshoku/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/numo-narray-0.9.1.9/lib/numo/narray/extra.rb:1116: warning: Using the last argument as keyword parameters is deprecated
=>
Numo::DFloat#shape=[1]
[32]
```
This PR:
```ruby
irb(main):001:0> require 'numo/narray'
=> true
irb(main):002:0> a=Numo::Int32[1,2,3]
=>
Numo::Int32#shape=[3]
...
irb(main):003:0> b=Numo::DFloat[[4],[5],[6]]
=> …
```
> Use rb_funcallv_kw function when calling method with keyword arguments

- ext/numo/narray/numo/types/complex_macro.h
- ext/numo/narray/numo/types/float_macro.h
Currently, `numpy.sinc(0.0)` returns 1.0, while `Numo::NMath.sinc(0.0)` returns NAN.
In this patch allows to return 1.0 in `Numo::NMath.sinc(0.0)`, just like `numpy.sinc(0.0)`.
> Fix NMath.sinc(0)

- ext/numo/narray/narray.c
Hi there.
With the help of [yard-junk](https://github.com/zverok/yard-junk) created by @zverok, I found a very trivial typo in the yard doc.
I'm happy to send a pull request to numo-narray. 
(It's not a very meaningful pull request, though.)
Thank you for your maintaining numo-narray.
> Fix a typo

- ext/numo/narray/gen/def/bit.rb
Hi.
I am looking at the source code of numo-narray now.
I noticed that among the files in the def directory, only bit.rb does not align the lines. I think this is probably not intentional. This is just a minor style correction, but it would be nice if you could merge it.
Thank you.
> Align lines of code

- ext/numo/narray/array.c
Hello.
Thank you for maintaining this wonderful library.
Understanding the source code of Numo::NArray, even partially, has been a dream of mine since I started programming.
When I compiled NArray from the source code, I noticed the following warning.
```console
../../../../../ext/numo/narray/array.c:361:5: warning: ‘rb_cData’ is deprecated: by: rb_cObject.  Will be removed in 3.1. [-Wdeprecated-declarations]
361 |     vmdai = TypedData_Wrap_Struct(rb_cData, &mdai_data_type, (void*)mdai);
|     ^~~~~
```
https://github.com/ruby-numo/numo-narray/blob/6f5c91250c0cb948f6b811385d384c3f15af4dcd/ext/numo/narray/array.c#L361
So we created a pull request to change rb_cData to rb_cObject.
This is the first pull request for the Numo::NArray C code. Please check if this simple replacement is …
> Use rb_cObject instead of rb_cData

- .github/workflows/build.yml
- ext/numo/narray/array.c
- lib/numo/narray.rb
Adds Windows and macOS CI jobs.  Ruby master/head testing is much better than in the past, as all the Ruby builds are fully tested on GitHub Actions.  With other CI systems, that was not the case.  Many repos are testing against the builds without 'allow-failure' setups.
Small update to array.c, same as #201 (gave co-author credit)
Closes #200
Closes #201
Passing CI - see https://github.com/MSP-Greg/numo-narray/actions/runs/2673530157
> Add Windows & macOS to CI, fix Ruby master issue

- ext/numo/narray/gen/tmpl/alloc_func.c
- ext/numo/narray/gen/tmpl/init_class.c
- ext/numo/narray/narray.c
- ext/numo/narray/numo/narray.h
- numo-narray.gemspec
- test/ractor_test.rb
- test/test_helper.rb
I want to let numo-narray support Ractor in this pull request.
The following changes are made:
- Freeze `UPCAST` constants to make them sharable in non-main Ractors
- Make frozen narrays sharable with non-main Ractors except for instances of `Numo::RObject`
I keep `Numo::RObject` non-sharable because its instances can have compound objects such as `Array` and `Hash`.
@masa16 Could you please take a look?
> Ractor support

- .github/workflows/build.yml
- ext/numo/narray/extconf.rb
- ext/numo/narray/index.c
- ext/numo/narray/numo/narray.h
- ext/numo/narray/step.c
- numo-narray.gemspec
This PR will fix  CI failures and improve Ruby 3.3 support.
1. Remove bundler installation
- It installs bundler without specifying the version in CI. But, it installs bundler which does not work with old Ruby, and it causes failure. So, this patch remove bundler installation and uses bundler bundled in Ruby.
2. Fix failure with Ruby 3.3
- The method of getting pointers from TypedData structure has changed since Ruby 3.3. This PR follows that.
> Fix CI failures and improve Ruby 3.3 support

- .github/workflows/build.yml
Check builds with new C compilers.
> Add tests on Fedora

- ext/numo/narray/numo/types/float_macro.h
- test/narray_test.rb
```
% irb -rnumo/narray
irb(main):001:0> Numo::DFloat[1, nil, 3]
(irb):1:in `[]': no implicit conversion to float from nil (TypeError)
from (irb):1:in `<main>'
from /Users/mrkn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
from /Users/mrkn/.rbenv/versions/3.1.2/bin/irb:25:in `load'
from /Users/mrkn/.rbenv/versions/3.1.2/bin/irb:25:in `<main>'
irb(main):002:0> Numo::RObject[1, nil, 3].cast_to(Numo::DFloat)
(irb):2:in `cast': no implicit conversion to float from nil (TypeError)
from (irb):2:in `cast_to'
from (irb):2:in `<main>'
from /Users/mrkn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
from /Users/mrkn/.rbenv/versions/3.1.2/bin/irb:25:in `load'
from /Users/mrkn/.rbenv/versions/3.1.2/bin/irb:25:in …
```
> Allow convert nil to NaN when making Numo::DFloat

- .github/workflows/build.yml
- ext/numo/narray/ndloop.c
- ext/numo/narray/numo/types/xint_macro.h
- test/narray_test.rb
This master pull request is to ensure that all tests pass when the pull requests I submitted today are merged.
Thank you.
> Integrate pull requests and verify that all tests pass

- test/bit_test.rb
- Regression test was using `Numo::Int32` instead of `Numo::Bit`
- Changed to use Numo::Bit to match the original bug report 
- #172
> Fix regression test for Issue #172

- .gitignore
Add `lib/numo/numo/extconf.h` to `.gitignore`.
- This file is generated by rake-compiler during `bundle exec rake compile`
- It was missed when rake-compiler was added in c0641fc (2020)
- Build-generated files should not be tracked in git
Thank you.
> Ignore auto-generated extconf.h in lib directory
